@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package phrille.vanillaboom.handler;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;