@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package phrille.vanillaboom.block;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;