@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package phrille.vanillaboom.inventory;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;