@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package phrille.vanillaboom.inventory.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;