@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package phrille.vanillaboom.mixin;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;